### ISSUE TITLE
Use int versions instead of strings

### ISSUE THREAD

**Issue by carlosms** [src-d/metadata-retrieval#11]
Right now the schema from #1 uses strings as versions. Probably a column with an array of ints will be faster to filter than an array of strings.

We might want to deal only with numbers, or maybe we can have a new table with extra information: the version int ID, a string name, maybe a timestamp of when it was created, a bool if it's the current version or not...

**Comment by se7entyse7en** [comment]
Having another table with the versions metadata could be helpful. One case that comes to my mind is to show how much fresh is the metadata, and eventually, we could also provide a way to force-refresh them (if this is something compatible with the DR architecture.)
