### ISSUE TITLE
Refactor methods for pagination

### ISSUE THREAD

**Issue by carlosms** [src-d/metadata-retrieval#12]
The code from #1 contains a lot of copy & paste code for all the pagination loops.
This issue is to try to refactor it into something cleaner and generic.

Also, the pagination can be improved to be aware of how many elements we already retrieved, and how many are left.
For example, for a repository with 140 issues, maybe we can have a good default for the first page of 20. The `totalCount` returns 140, so we know we can do another query of 100 and another one of 20.

**Comment by dpordomingo** [comment]
Why not doing an initial call to count all the resources (issues, repos, and topics), and then proceed with the download?
If we do not want this initial call, why not requesting the first 100 resources instead of only 20?

**Comment by se7entyse7en** [comment]
> If we do not want this initial call, why not requesting the first 100 resources instead of only 20?

I don't remember if it was explained in some minutes or maybe it has been lost in some slack thread. But the problem is that that quota counts based on the number of _potential_ nodes returned and not based on the number of _actual_ nodes. So requesting the first `n` resources when they're actually `m << n` it's a waste. That's why 20 has been proposed as a _reasonable_ default value.

**Comment by se7entyse7en** [comment]
@dpordomingo Maybe my terminology it's not much correct (I'm also not a graphql expert). What I meant with _potential_ is that if for example I run this:

```
{
  viewer {
    login
    repositories(first: 100, isFork: false) {
      totalCount
      edges {
        node {
          id
          issues(first: 50) {
            edges {
              node {
                id
                comments(first: 90) {
                  edges {
                    node {
                      id
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

I can clearly see `totalCount: 29`, but the cost of this is still `51 = (1 + 100 + 5000) / 100`, when I'd have obtained the same output by setting `first: 29` with a cost of `15 = (1 + 100 + 1450) / 100`.
