### ISSUE TITLE
Change GH metadata schema to fit the common schema

### ISSUE THREAD

**Issue by se7entyse7en** [src-d/metadata-retrieval#35]
DD: [private] [link](https://docs.google.com/document/d/1quecdJyZhWPzGLLYRk7FhHP7XgcrPgEE5HFvsdOOYU4/edit?ts=5d9efb0c)

The above DD has been approved by @src-d/product. We can start changing the schema for GH metadata to fit the unified one.

**Comment by smacker** [comment]
todo:
- update current testsuite
- create new test suite for new schema
- manual testing
