### ISSUE TITLE
Choose a license for the repository

### ISSUE THREAD

**Issue by carlosms** [src-d/metadata-retrieval#5]
Quoting @smola https://github.com/src-d/metadata-retrieval/pull/4#issuecomment-534955246
> I think we'll need Apache 2.0 license here (to import on proprietary code)

**Comment by se7entyse7en** [comment]
This has been unblocked, see [here](https://src-d.slack.com/archives/C7TB5NEDN/p1571761373217500?thread_ts=1571757452.213500&channel=C7TB5NEDN&message_ts=1571761373.217500).
