### ISSUE TITLE
Deal with tokens with missing scopes

### ISSUE THREAD

**Issue by carlosms** [src-d/metadata-retrieval#7]
This issue is to move a conversation started in #1, and decide if we want to change anything when the token used does not have enough scopes:

@carlosms 
> I've commented out a couple of fields, and now the scope needs to be only read:org, repo

@smacker 
> Cool. REST API is smart enough to return only fields that a token permits. So we can do a similar thing on our side. Check permissions of the token and depending on it request some fields or not.
> On another hand, I would prefer to just remove such fields if we don't really need them.

@carlosms  
> I think this can be problematic. If we silently skip some fields automatically depending on the token scopes, sourced CE/EE might end with dashboards that don't work without any error message anywhere.
> I agree that the proper solution is to take the scopes into consideration when we transition from the ghsync schema to a proper one.

@smacker 
> yeah. We can make it smarter than silently skipping. I'm just saying it works right now with ghsync so we might want to consider something similar (and maybe reject the idea). It is also good to know as we download data for demos using multiple tokens. For example, my token never had any permissions and @se7entyse7en's could have. So some part of the data can contain the field and another not.

For me, personally, the option that makes sense is to move to a schema with the minimum amount of data that makes sense. And guarantee that all the fields will be downloaded always. The code should fail when the token does not allow to download the data we "promise".

**Comment by smacker** [comment]
I see how `email` field in users can be useful (which is commented now).
For our current dashboards we don't need it but custom dashboards could require it.

**Comment by smacker** [comment]
Okay, I calculated some stat using data from GHTorrent and BigQuery because it's fun.

Only the organizations that have all issues, prs, issue comments, pr comments.
It doesn't count code reviews as I don't see such table (maybe possible to get from `history` table but I didn't explore it).

Results:

Bucket is a sum of all those resources. Num is a number of such orgs.

bucket | num 
-------| ---	 
5000   | 11890 	 
10000  | 537 	
15000  | 224 
50000  | 208 
20000  | 110 	 
100000 | 60
More   | 28 	 


<details><summary>SQL Query</summary>
<p>

.

```sql
#standardSQL
SELECT
    CASE
    WHEN total < 5001 THEN '5000'
    WHEN total > 5001 AND total < 10001 THEN '10000'
    WHEN total > 10001 AND total < 15001 THEN '15000'
    WHEN total > 15001 AND total < 20001 THEN '20000'
    WHEN total > 20001 AND total < 50001 THEN '50000'
    WHEN total > 50001 AND total < 100001 THEN '100000'
    ELSE 'More'
    END AS bucket,
    COUNT(*) as num
FROM (
    SELECT prsq.login, issues_num, issues_comments_num, prs_num, pr_comments_num,
    (issues_num + issues_comments_num + prs_num + pr_comments_num) AS total
    FROM (
        SELECT u.login, COUNT(pr.id) AS prs_num
        FROM `ghtorrent-bq.ght.pull_requests` pr
        JOIN `ghtorrent-bq.ght.projects` p ON p.id = pr.head_repo_id
        JOIN `ghtorrent-bq.ght.users` u ON u.id = p.owner_id
        WHERE p.forked_from IS NULL
        AND p.deleted = FALSE
        AND u.deleted = FALSE
        AND u.type = 'ORG'
        GROUP BY u.login
    ) prsq
    JOIN (
        SELECT u.login, COUNT(issue.id) AS issues_num
        FROM `ghtorrent-bq.ght.issues` issue
        JOIN `ghtorrent-bq.ght.projects` p ON p.id = issue.repo_id
        JOIN `ghtorrent-bq.ght.users` u ON u.id = p.owner_id
        WHERE issue.pull_request = FALSE
        AND p.forked_from IS NULL
        AND p.deleted = FALSE
        AND u.deleted = FALSE
        AND u.type = 'ORG'
        GROUP BY u.login
    ) issuesq ON prsq.login = issuesq.login
    JOIN (
        SELECT u.login, COUNT(ic.comment_id) AS issues_comments_num
        FROM `ghtorrent-bq.ght.issue_comments` ic
        JOIN `ghtorrent-bq.ght.issues` issue ON issue.id = ic.issue_id
        JOIN `ghtorrent-bq.ght.projects` p ON p.id = issue.repo_id
        JOIN `ghtorrent-bq.ght.users` u ON u.id = p.owner_id
        WHERE p.forked_from IS NULL
        AND p.deleted = FALSE
        AND u.deleted = FALSE
        AND u.type = 'ORG'
        GROUP BY u.login
    ) icq ON prsq.login = icq.login
    JOIN (
        SELECT u.login, COUNT(prc.comment_id) AS pr_comments_num
        FROM `ghtorrent-bq.ght.pull_request_comments` prc
        JOIN `ghtorrent-bq.ght.pull_requests` pr ON pr.id = prc.pull_request_id
        JOIN `ghtorrent-bq.ght.projects` p ON p.id = pr.head_repo_id
        JOIN `ghtorrent-bq.ght.users` u ON u.id = p.owner_id
        WHERE p.forked_from IS NULL
        AND p.deleted = FALSE
        AND u.deleted = FALSE
        AND u.type = 'ORG'
        GROUP BY u.login
    ) prcq ON prsq.login = prcq.login
) dq
GROUP BY bucket
LIMIT 10
```

</p>
</details>

We actually make a bit more requests like getting lables and users and maybe something more.
If you want I can try to make the result closer to our use case.

Still I think this numbers show that it makes sense to have both multiple tokens and parallel downloading.

**Comment by se7entyse7en** [comment]
> For me, personally, the option that makes sense is to move to a schema with the minimum amount of data that makes sense. And guarantee that all the fields will be downloaded always. The code should fail when the token does not allow to download the data we "promise".

I agree with these. One we have decided the common schema between the 3 main providers we could verify which permissions are required to get all those fields.
