### ISSUE TITLE
Add support for multiple tokens in the example cmd

### ISSUE THREAD

**Issue by carlosms** [src-d/metadata-retrieval#9]
Make the command accept a list of token strings.
Relevant comment, with link to a previous implementation for ghsync: https://github.com/src-d/metadata-retrieval/issues/3#issuecomment-534926905

**Comment by se7entyse7en** [comment]
Given our discovery in #19, I'd just add multi-token to be used serially for now. It will already improve the experience for demo preparation.

**Comment by se7entyse7en** [comment]
For some reason, this hasn't been closed when #28 has been merged...
